######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 26 15:53:59 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . image
INCLUDEPATH += .

# Input
HEADERS += logo.h mainwindow.h smallwindow.h widget.h
FORMS += logo.ui mainwindow.ui smallwindow.ui widget.ui
SOURCES += logo.cpp main.cpp mainwindow.cpp smallwindow.cpp widget.cpp
RESOURCES += image/res.qrc
