#############################################################################
# Makefile for building: Linux_Music_project
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? 10? 26 15:54:25 2020
# Project:  Linux_Music_project.pro
# Template: app
# Command: /usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/qmake -o Makefile Linux_Music_project.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/qt_cortex-a8_4.3.2/include/QtCore -I/usr/local/Trolltech/qt_cortex-a8_4.3.2/include/QtNetwork -I/usr/local/Trolltech/qt_cortex-a8_4.3.2/include/QtGui -I/usr/local/Trolltech/qt_cortex-a8_4.3.2/include -I. -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib -lQtGui -L/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = logo.cpp \
		main.cpp \
		mainwindow.cpp \
		smallwindow.cpp \
		widget.cpp moc_logo.cpp \
		moc_mainwindow.cpp \
		moc_smallwindow.cpp \
		moc_widget.cpp \
		qrc_res.cpp
OBJECTS       = logo.o \
		main.o \
		mainwindow.o \
		smallwindow.o \
		widget.o \
		moc_logo.o \
		moc_mainwindow.o \
		moc_smallwindow.o \
		moc_widget.o \
		qrc_res.o
DIST          = /usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/qws.conf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/include_source_dir.prf \
		Linux_Music_project.pro
QMAKE_TARGET  = Linux_Music_project
DESTDIR       = 
TARGET        = Linux_Music_project

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_logo.h ui_mainwindow.h ui_smallwindow.h ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Linux_Music_project.pro  /usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/qws.conf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib/libQtGui.prl \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib/libQtNetwork.prl \
		/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib/libQtCore.prl
	$(QMAKE) -o Makefile Linux_Music_project.pro
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/g++.conf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/unix.conf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/linux.conf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/common/qws.conf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/qconfig.pri:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/release.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/default_post.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/qt.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/moc.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/resources.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/uic.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/yacc.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/lex.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib/libQtGui.prl:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib/libQtNetwork.prl:
/usr/local/Trolltech/qt_cortex-a8_4.3.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Linux_Music_project.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Linux_Music_project1.0.0 || $(MKDIR) .tmp/Linux_Music_project1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Linux_Music_project1.0.0/ && $(COPY_FILE) --parents logo.h mainwindow.h smallwindow.h widget.h .tmp/Linux_Music_project1.0.0/ && $(COPY_FILE) --parents image/res.qrc .tmp/Linux_Music_project1.0.0/ && $(COPY_FILE) --parents logo.cpp main.cpp mainwindow.cpp smallwindow.cpp widget.cpp .tmp/Linux_Music_project1.0.0/ && $(COPY_FILE) --parents logo.ui mainwindow.ui smallwindow.ui widget.ui .tmp/Linux_Music_project1.0.0/ && (cd `dirname .tmp/Linux_Music_project1.0.0` && $(TAR) Linux_Music_project1.0.0.tar Linux_Music_project1.0.0 && $(COMPRESS) Linux_Music_project1.0.0.tar) && $(MOVE) `dirname .tmp/Linux_Music_project1.0.0`/Linux_Music_project1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Linux_Music_project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_logo.cpp moc_mainwindow.cpp moc_smallwindow.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_logo.cpp moc_mainwindow.cpp moc_smallwindow.cpp moc_widget.cpp
moc_logo.cpp: logo.h
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/moc $(DEFINES) $(INCPATH) logo.h -o moc_logo.cpp

moc_mainwindow.cpp: mainwindow.h
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_smallwindow.cpp: smallwindow.h
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/moc $(DEFINES) $(INCPATH) smallwindow.h -o moc_smallwindow.cpp

moc_widget.cpp: smallwindow.h \
		logo.h \
		mainwindow.h \
		widget.h
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: image/res.qrc \
		image/close.png \
		image/play1.png \
		image/sound2.png \
		image/sing.png \
		image/friend.png \
		image/load.png \
		image/privateFM.png \
		image/logo.png \
		image/style2.jpg \
		image/music.png \
		image/sound1.png \
		image/play2.png \
		image/search.png \
		image/set.png \
		image/suspend.png \
		image/style1.jpg \
		image/small.png \
		image/radio.png \
		image/narrow.png \
		image/list.png \
		image/next.png \
		image/play3.png \
		image/big.png \
		image/localM.png \
		image/transparent.png \
		image/clothes.png \
		image/mail.png \
		image/last.png \
		image/play4.png \
		image/sound3.png \
		image/res.qrc \
		image/play.png \
		image/favorite.png \
		image/style3.jpg \
		image/sound.png
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/rcc -name res image/res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_logo.h ui_mainwindow.h ui_smallwindow.h ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_logo.h ui_mainwindow.h ui_smallwindow.h ui_widget.h
ui_logo.h: logo.ui
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/uic logo.ui -o ui_logo.h

ui_mainwindow.h: mainwindow.ui
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_smallwindow.h: smallwindow.ui
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/uic smallwindow.ui -o ui_smallwindow.h

ui_widget.h: widget.ui \
		mainwindow.h
	/usr/local/Trolltech/qt_cortex-a8_4.3.2/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

logo.o: logo.cpp logo.h \
		ui_logo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logo.o logo.cpp

main.o: main.cpp widget.h \
		smallwindow.h \
		logo.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

smallwindow.o: smallwindow.cpp smallwindow.h \
		widget.h \
		logo.h \
		mainwindow.h \
		ui_smallwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smallwindow.o smallwindow.cpp

widget.o: widget.cpp widget.h \
		smallwindow.h \
		logo.h \
		mainwindow.h \
		ui_widget.h \
		ui_smallwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_logo.o: moc_logo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logo.o moc_logo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_smallwindow.o: moc_smallwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_smallwindow.o moc_smallwindow.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

